version: '3.8'

services:
    postgres:
        container_name: postgres-server-crawler
        image: postgres:15.3
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
            - postgres_data:/var/lib/postgresql/data
        networks:
            - network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 2s
            timeout: 3s
            retries: 40

networks:
    network:
        driver: bridge

volumes:
    postgres_data: